class SkeletonGenerated
  def call(user)
    # some code that actually got added 
    #after auto generating the class
    retunr 'I\'m doing my part!'
  end
end

describe SkeletonGenerated do
  subject { described_class }

  # TODO: this is an autogenerated 
  # test placeholder.
end
